### PR TITLE
Allow custom syslog rule for forwarding

### PR DESCRIPTION
**Pull request by ronakbanka**
This PR will add option to add any optional forwarding rules .

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ronakbanka Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf-experimental/kubo-release&pullRequestId=22)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf-experimental/kubo-release&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ronakbanka Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf-experimental/kubo-release&pullRequestId=22)!

**Comment by jhvhs** [comment]
Hi @ronakbanka,

Thank you very much for your contribution. 
Could you please explain the rationale behind this change?
It seems a little bit too broad.

**Comment by ronakbanka** [comment]
@jhvhs We are using omkafka package to forward syslog stream to Kafka brokers , so instead of setting a syslog endpoint we add the custom rule with configuration.
Reference: http://www.rsyslog.com/doc/master/configuration/modules/omkafka.html

**Comment by alex-slynko** [comment]
Hi @ronakbanka 
Sorry for taking so long with answer.
We investigated syslog support and have decided that we will drop it from `kubo-release`. You have to use [syslog-release](https://github.com/cloudfoundry/syslog-release) to forward logs to syslog. It does have the functionality you need.

**Pull request closed without merging**
